
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 115
#define YY_END_OF_BUFFER 116
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[507] =
    {   0,
        0,    0,  116,  114,  113,    9,  114,  114,  114,  114,
      114,  114,   40,   41,   45,   47,   39,   48,   38,   46,
      110,  110,   49,   44,   50,  111,   42,   43,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  113,
        9,   54,    0,    1,    0,    0,    5,    0,  110,    0,
      109,    0,    0,  109,  110,  110,  110,  110,   52,   51,
       53,  111,    0,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,   22,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

       37,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  110,  111,    0,  112,
        0,    0,    0,    0,    6,    0,   55,    0,   36,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
       78,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
       20,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,    2,    0,    0,    0,    0,    0,
        8,    0,    4,    0,    0,    3,    0,  111,   21,  111,

      111,  111,  111,  111,   24,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,   77,  111,  111,  111,  111,  111,  111,
      111,  111,  111,   28,  111,  111,  111,  111,  111,  111,
       11,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,   73,  111,  111,  111,   23,  111,   10,   12,   99,
      111,   87,    0,    8,    7,   35,  111,   61,  111,  111,
      111,  111,  111,  111,  111,   26,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,

      111,  111,   19,  111,  111,  111,   98,  111,  111,  111,
      111,  111,  111,  111,  111,  111,   66,  111,  111,  103,
       32,  111,  111,   85,  111,  111,  111,  111,   25,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
      108,  111,   79,  111,   81,  111,  111,  111,  111,   56,
       74,   14,  111,  111,  111,  111,  111,   59,  111,   27,
      111,   60,   68,  111,  111,  111,  111,  111,  111,  111,
      111,  111,  111,  111,  111,   29,  111,  111,  111,  111,
      111,  111,  111,   88,  111,  106,  111,   34,  111,  111,

       17,  111,  111,  111,   62,   63,  111,   31,   83,  111,
      111,   58,  111,   33,  111,  111,  111,   13,  101,   72,
      111,  111,  111,  111,  111,  111,  111,  111,  111,  111,
       67,  111,  111,   86,  107,   30,   92,   15,  111,  111,
      111,    0,   91,  105,  102,   97,  111,  111,  104,  111,
      111,  111,  111,   82,  111,  111,   57,   75,  111,   69,
      111,  111,   76,  111,   70,  111,  111,   93,  111,  111,
      111,   18,  111,   65,   84,  111,  111,  111,  111,  111,
        0,   80,  111,   16,  111,  111,  111,  100,  111,  111,
      111,  111,   71,   95,  111,   64,   96,  111,  111,   89,

      111,  111,   94,  111,   90,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   20,   20,    1,    1,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   24,   24,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       26,   27,   28,    1,   29,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   46,   47,   48,   49,   50,   51,   52,   53,
       54,   55,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[56] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    4,    1,    5,    5,    5,
        1,    1,    1,    5,    6,    1,    1,    1,    7,    5,
        5,    5,    5,    5,    5,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6,    6,    6,    6,    6,    6,
        6,    6,    6,    6,    6
    } ;

static yyconst flex_int16_t yy_base[521] =
    {   0,
        0,    0, 1066, 1067, 1063, 1067, 1061, 1041,   50,   54,
       41,    0, 1067, 1067, 1067, 1067, 1067, 1067,   44,   53,
       53,   60, 1040, 1039, 1038, 1030, 1067, 1067,   38,   45,
       53,   55,   61,   54,   57,   70,   59,   65,   73,   85,
       71,   75,   92,   98,  104,   91,  107,  141,   99, 1056,
     1067, 1067,  104, 1067,  137,  120, 1067,  141,  134, 1048,
      137, 1044,  174,  163,  169,  131, 1039,  174, 1067, 1067,
     1067, 1025, 1024,  133,  166,  167,  168,  169,  170,  172,
      134,  173,  178,  176,  180,  185,  186, 1023,  177,  195,
      189,   37,  196,  190,  202,  203,  207,  208,  209,  213,

     1022,  216,  217,  220,  222,  224,  226,  231,  227,  234,
      229,  242,  235,  238,  250,  257,    0,  248,  267, 1067,
     1041, 1037,  276,  286, 1067,  292,  294,  296, 1019,  272,
      263,  274,  276,  277,  279,  280,  281,  298,  282,  285,
      289,  287,  283,  296,  306,  314,  301,  295,  321,  322,
      300,  319,  328,  329,  331,  333,  334,  335,  336,  338,
      339,  342,  343,  348,  345,  350,  351,  352,  356,  353,
     1018,  358,  359,  363,  366,  370,  364,  360,  368,  377,
      381,  379,  383,  385, 1067,    0, 1037,  406, 1033,  407,
     1032,  417, 1067,  422,  425, 1067,  429,  393, 1014,  401,

      405,  406,  407,  408,  410,  411,  413,  416,  417,  415,
      432,  425,  426,  433,  439,  436,  420,  422,  442,  444,
      448,  450,  451, 1013,  454,  455,  457,  460,  456,  461,
      467,  471,  469, 1012,  464,  472,  477,  478,  480,  482,
     1011,  485,  487,  490,  492,  494,  488,  493,  495,  496,
      504, 1010,  508,  509,  510, 1009,  511, 1008, 1007, 1006,
      513, 1005, 1024, 1020, 1019, 1001,  514, 1000,  512,  516,
      518,  519,  520,  521,  527,  999,  529,  534,  530,  533,
      543,  522,  541,  546,  538,  550,  552,  554,  548,  557,
      559,  558,  560,  561,  567,  570,  574,  571,  576,  577,

      578,  583,  998,  581,  587,  588,  997,  586,  579,  589,
      594,  597,  599,  601,  604,  603,  996,  607,  605,  995,
      994,  611,  606,  993,  614,  613,  615,  620,  992,  616,
      623,  622,  629,  632,  630,  636,  638,  640,  641,  642,
      643,  645,  644,  647,  649,  654,  655,  653,  656,  662,
      666,  668,  991,  667,  990,  670,  674,  675,  676,  989,
      988,  987,  680,  682,  683,  688,  681,  986,  690,  684,
      691,  985,  984,  694,  692,  693,  699,  702,  705,  704,
      706,  709,  712,  716,  719,  983,  717,  721,  723,  725,
      728,  727,  729,  982,  736,  981,  735,  980,  738,  737,

      979,  739,  743,  742,  978,  977,  746,  976,  975,  744,
      754,  974,  755,  973,  756,  757,  758,  972,  971,  970,
      759,  764,  761,  760,  765,  771,  768,  776,  779,  781,
      969,  767,  782,  968,  967,  966,  788,  965,  789,  791,
      792,  793,  964,  963,  962,  961,  794,  796,  960,  798,
      801,  799,  803,  959,  804,  806,  958,  957,  810,  954,
      812,  813,  933,  816,  929,  818,  820,  915,  819,  824,
      826,  911,  827,  904,  879,  828,  833,  834,  835,  837,
      841,  878,  842,  877,  845,  843,  851,  876,  857,  849,
      847,  853,  875,  874,  859,  873,  291,  860,  866,  140,

      867,  868,  111,  869,   63, 1067,  910,  917,  920,  923,
      924,  931,  936,  942,  949,  954,  960,  967,  974,  979
    } ;

static yyconst flex_int16_t yy_def[521] =
    {   0,
      506,    1,  506,  506,  506,  506,  506,  506,  507,  508,
      506,  509,  506,  506,  506,  506,  506,  506,  506,  506,
      510,  506,  506,  506,  506,  511,  506,  506,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  506,
      506,  506,  507,  506,  512,  508,  506,  508,  506,  513,
      506,  514,  515,  506,  510,   65,  510,  506,  506,  506,
      506,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,

      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,   48,  511,  512,  506,
      516,  514,  517,  515,  506,  515,  518,  519,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  506,  512,  520,  514,  517,  517,
      517,  518,  506,  518,  519,  506,  519,  511,  511,  511,

      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  506,  514,  517,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,

      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,

      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,
      511,  511,  511,  511,  511,  511,  511,  511,  511,  511,

      511,  511,  511,  511,  511,    0,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506
    } ;

static yyconst flex_int16_t yy_nxt[1123] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       23,   24,   25,   26,   26,   27,    4,   28,    4,   29,
       26,   30,   31,   32,   33,   34,   35,   36,   26,   37,
       38,   39,   40,   41,   42,   26,   43,   44,   45,   46,
       47,   26,   48,   26,   49,   54,   57,   58,   59,   59,
       59,   61,   61,   61,   62,   73,   73,  152,   64,   63,
       65,   65,   66,   73,   76,   64,   55,   68,   68,   68,
       74,   73,   73,   73,   75,   73,   78,   73,   77,   73,
       84,   73,   91,   73,   86,   80,   79,   81,   73,   73,

       87,   73,   92,   73,   88,   82,   94,   83,   93,   54,
       85,   89,   90,   73,   96,  100,   95,  101,   97,   73,
       73,  102,   57,   58,  103,  104,   73,   73,   98,  106,
       55,  107,   73,  110,   99,   73,  118,  111,  115,   73,
      112,  105,   53,   57,   58,  116,  108,  109,   66,   66,
      113,   59,   59,   59,   61,   61,   61,  114,  117,  117,
      117,   73,   73,   53,  117,  129,  138,   53,   73,   73,
      117,  117,  117,  117,  117,  117,  125,  126,  127,   53,
       61,   61,   61,   53,   64,   53,   65,   65,   66,   64,
      128,   68,   68,   68,   73,   73,   73,   73,   73,  133,

       73,   73,  139,  134,   73,   73,   73,  131,   73,  135,
      132,  140,  130,   73,   73,  141,  143,   73,   73,  137,
      136,  147,  144,   73,   73,  153,  142,  154,  145,  146,
       73,   73,  148,  149,  157,   73,   73,   73,  156,  155,
      159,   73,  151,  150,   73,   73,  163,  166,   73,  162,
       73,  158,   73,  165,   73,   73,  160,   73,  161,   73,
      172,  164,   73,   73,  169,  167,   73,  170,  168,  119,
       73,  175,  185,  176,  171,  178,   73,  173,   73,  179,
      174,  177,  181,  182,  180,   73,  183,  190,  125,  126,
      184,   73,  191,  186,  125,  126,  193,  194,  196,  197,

       73,  198,   73,  199,   73,   73,  202,   73,   73,   73,
       73,   73,  203,   73,  205,   73,  218,   73,  204,   73,
      220,  200,  217,   73,   73,  201,   73,  222,   73,   73,
      221,  206,  207,  208,   73,  209,  223,  219,  210,  211,
      212,  225,   73,  227,  226,  213,  214,   73,  215,   73,
       73,  230,  216,  224,  228,  229,   73,   73,  233,   73,
      232,   73,   73,   73,   73,  231,   73,   73,  238,  235,
       73,   73,  237,   73,  239,  234,   73,  240,   73,   73,
       73,   73,  241,  236,   73,  243,   73,   73,   73,  242,
      245,   73,   73,  252,   73,  244,   73,  249,   73,  253,

      246,  247,  256,  254,  248,   73,  250,   73,  251,   73,
      258,   73,  255,   73,  259,  257,  262,  188,  190,  193,
      194,   73,  264,  265,  193,  194,  260,  196,  197,   73,
      261,  196,  197,   73,   73,   73,   73,  271,   73,   73,
      268,   73,  270,   73,   73,   73,  266,  272,   73,  267,
       73,  276,  278,   73,   73,  269,  275,  283,  279,  277,
       73,   73,  274,  273,   73,  280,  285,   73,  282,  288,
       73,  289,   73,  287,  284,  281,   73,  286,   73,   73,
      294,  258,   73,   73,   73,   73,  291,  295,   73,   73,
      292,  298,   73,  290,  297,   73,  301,   73,  293,   73,

       73,  296,  299,  302,  300,   73,   73,  304,   73,  303,
       73,  309,  305,   73,  310,   73,   73,  308,   73,  312,
       73,   73,   73,   73,   73,  307,  316,  306,  317,  313,
      311,  314,   73,  318,  315,  319,   73,   73,   73,   73,
       73,   73,   73,  325,   73,  327,   73,   73,   73,   73,
       73,  322,  326,  329,  320,   73,  321,   73,   73,  323,
      324,   73,   73,  331,  335,  328,   73,  333,  330,   73,
      332,   73,  339,  336,   73,  338,   73,  334,   73,  343,
       73,  337,   73,  345,  340,   73,   73,   73,   73,   73,
      342,  348,  341,  347,  344,   73,  346,  350,   73,   73,

      349,  351,   73,  354,   73,   73,   73,   73,  352,   73,
      356,   73,  359,  360,   73,   73,   73,   73,  353,  355,
      361,  362,   73,  357,  358,   73,  364,   73,  363,   73,
      368,   73,   73,   73,   73,   73,  366,  365,  372,   73,
      374,   73,   73,   73,   73,  367,  370,  369,   73,  380,
       73,   73,  382,  373,  381,  371,  376,   73,   73,  375,
       73,  377,  383,  378,   73,  384,   73,  379,   73,   73,
       73,   73,   73,   73,  387,   73,  385,   73,  394,  389,
      386,   73,   73,   73,   73,  399,  390,  396,  397,  388,
       73,  393,  391,  392,   73,   73,   73,  395,   73,  404,

      398,  402,   73,   73,   73,  400,  405,  403,   73,   73,
       73,   73,   73,  401,  412,  408,   73,  411,   73,   73,
       73,   73,   73,  413,  407,  416,  410,   73,  406,  409,
       73,  414,   73,   73,   73,  420,  417,   73,  424,  415,
       73,  418,  421,  425,   73,   73,  419,   73,  427,   73,
      422,   73,  430,   73,  423,   73,   73,   73,  431,  432,
      428,  429,  426,   73,   73,   73,   73,   73,  433,  435,
       73,   73,   73,  441,   73,  443,  434,  436,  437,  438,
      440,  439,   73,   73,   73,   73,   73,   73,   73,   73,
      444,  449,   73,   73,  445,   73,   73,  447,  452,   73,

      453,  450,  446,  448,   73,  455,  451,   73,  457,   73,
       73,  461,  458,  454,  456,  460,   73,   73,  462,   73,
       73,   73,   73,  467,   73,  465,   73,   73,  459,   73,
      470,   73,   73,  473,   73,  469,  466,  463,   73,  468,
       73,   73,  471,  476,   73,  464,   73,   73,   73,  478,
      472,  480,   73,  477,   73,   73,   73,  475,  485,  474,
      479,   73,   73,   73,  483,   73,  489,  482,  484,   73,
       73,   73,  492,   73,  486,   73,  487,   73,  493,   73,
      488,   73,  495,  490,  491,   73,  494,   73,   73,  498,
      496,  501,  497,  499,   73,   73,   73,   73,  500,  504,

      503,   73,   73,   73,   73,   73,   73,   73,  505,  502,
       53,   53,   53,   53,   53,   53,   53,   56,   56,   56,
       56,   56,   56,   56,   60,   60,   67,   67,   72,   72,
       72,  119,   73,  119,  119,  119,  119,  119,  121,   73,
      121,  121,  122,  481,  122,  122,  122,  122,  122,  124,
      124,  124,  124,  124,  124,  124,  187,   73,  187,  187,
      189,   73,  189,  189,  189,  189,  189,  192,  192,  192,
      192,  192,  192,  192,  195,  195,  195,  195,  195,  195,
      195,  263,   73,  263,  263,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,

       73,   73,   73,   73,   73,  442,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
      190,  188,  120,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,  190,  190,  120,   73,   73,  188,  120,
       73,   73,   73,   73,  506,  123,  120,   50,   73,   71,
       70,   69,   52,   51,   50,  506,    3,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506
    } ;

static yyconst flex_int16_t yy_chk[1123] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    9,   10,   10,   11,   11,
       11,   19,   19,   19,   20,   92,   29,   92,   21,   20,
       21,   21,   21,   30,   30,   22,    9,   22,   22,   22,
       29,   31,   34,   32,   29,   35,   31,   37,   30,   33,
       33,  505,   37,   38,   34,   32,   31,   32,   36,   41,

       35,   39,   38,   42,   36,   32,   39,   32,   38,   53,
       33,   36,   36,   40,   40,   41,   39,   41,   40,   46,
       43,   42,   56,   56,   42,   43,   44,   49,   40,   44,
       53,   44,   45,   45,   40,   47,   49,   45,   46,  503,
       45,   43,   55,   58,   58,   47,   44,   44,   66,   66,
       45,   59,   59,   59,   61,   61,   61,   45,   48,   48,
       48,   74,   81,   55,   48,   74,   81,   55,  500,   48,
       48,   48,   48,   48,   48,   48,   63,   63,   63,   55,
       64,   64,   64,   55,   65,   55,   65,   65,   65,   68,
       63,   68,   68,   68,   75,   76,   77,   78,   79,   78,

       80,   82,   82,   78,   84,   89,   83,   76,   85,   78,
       77,   83,   75,   86,   87,   83,   84,   91,   94,   80,
       79,   89,   85,   90,   93,   93,   83,   93,   86,   87,
       95,   96,   90,   90,   95,   97,   98,   99,   94,   93,
       97,  100,   91,   90,  102,  103,  100,  103,  104,   99,
      105,   96,  106,  102,  107,  109,   98,  111,   98,  108,
      108,  100,  110,  113,  105,  104,  114,  106,  104,  119,
      112,  109,  119,  110,  107,  112,  118,  108,  115,  112,
      108,  111,  114,  115,  113,  116,  116,  123,  124,  124,
      118,  131,  123,  119,  126,  126,  127,  127,  128,  128,

      130,  130,  132,  131,  133,  134,  134,  135,  136,  137,
      139,  143,  135,  140,  137,  142,  140,  141,  136,  497,
      142,  132,  139,  148,  144,  133,  138,  144,  151,  147,
      143,  138,  138,  138,  145,  138,  145,  141,  138,  138,
      138,  147,  146,  148,  147,  138,  138,  152,  138,  149,
      150,  151,  138,  146,  149,  150,  153,  154,  154,  155,
      153,  156,  157,  158,  159,  152,  160,  161,  159,  156,
      162,  163,  158,  165,  160,  155,  164,  161,  166,  167,
      168,  170,  162,  157,  169,  164,  172,  173,  178,  163,
      166,  174,  177,  174,  175,  165,  179,  170,  176,  175,

      167,  168,  178,  176,  169,  180,  172,  182,  173,  181,
      180,  183,  177,  184,  181,  179,  184,  188,  190,  192,
      192,  198,  188,  190,  194,  194,  182,  195,  195,  200,
      183,  197,  197,  201,  202,  203,  204,  204,  205,  206,
      201,  207,  203,  210,  208,  209,  198,  205,  217,  200,
      218,  209,  210,  212,  213,  202,  208,  213,  210,  209,
      211,  214,  207,  206,  216,  211,  214,  215,  212,  217,
      219,  218,  220,  216,  213,  211,  221,  215,  222,  223,
      223,  221,  225,  226,  229,  227,  220,  225,  228,  230,
      220,  228,  235,  219,  227,  231,  231,  233,  222,  232,

      236,  226,  229,  232,  230,  237,  238,  235,  239,  233,
      240,  240,  236,  242,  242,  243,  247,  239,  244,  244,
      245,  248,  246,  249,  250,  238,  248,  237,  249,  245,
      243,  246,  251,  250,  247,  251,  253,  254,  255,  257,
      269,  261,  267,  267,  270,  270,  271,  272,  273,  274,
      282,  255,  269,  272,  253,  275,  254,  277,  279,  257,
      261,  280,  278,  274,  278,  271,  285,  277,  273,  283,
      275,  281,  282,  279,  284,  281,  289,  277,  286,  286,
      287,  280,  288,  288,  283,  290,  292,  291,  293,  294,
      285,  291,  284,  290,  287,  295,  289,  293,  296,  298,

      292,  294,  297,  297,  299,  300,  301,  309,  295,  304,
      299,  302,  302,  304,  308,  305,  306,  310,  296,  298,
      305,  306,  311,  300,  301,  312,  309,  313,  308,  314,
      313,  316,  315,  319,  323,  318,  311,  310,  318,  322,
      322,  326,  325,  327,  330,  312,  315,  314,  328,  330,
      332,  331,  332,  319,  331,  316,  325,  333,  335,  323,
      334,  326,  333,  327,  336,  334,  337,  328,  338,  339,
      340,  341,  343,  342,  337,  344,  335,  345,  344,  339,
      336,  348,  346,  347,  349,  349,  340,  346,  347,  338,
      350,  343,  341,  342,  351,  354,  352,  345,  356,  356,

      348,  352,  357,  358,  359,  350,  357,  354,  363,  367,
      364,  365,  370,  351,  367,  363,  366,  366,  369,  371,
      375,  376,  374,  369,  359,  374,  365,  377,  358,  364,
      378,  370,  380,  379,  381,  378,  375,  382,  382,  371,
      383,  376,  379,  383,  384,  387,  377,  385,  385,  388,
      380,  389,  389,  390,  381,  392,  391,  393,  390,  391,
      387,  388,  384,  397,  395,  400,  399,  402,  392,  395,
      404,  403,  410,  404,  407,  407,  393,  397,  399,  400,
      403,  402,  411,  413,  415,  416,  417,  421,  424,  423,
      410,  417,  422,  425,  411,  432,  427,  415,  423,  426,

      424,  421,  413,  416,  428,  426,  422,  429,  428,  430,
      433,  433,  429,  425,  427,  432,  437,  439,  437,  440,
      441,  442,  447,  447,  448,  441,  450,  452,  430,  451,
      451,  453,  455,  455,  456,  450,  442,  439,  459,  448,
      461,  462,  452,  461,  464,  440,  466,  469,  467,  464,
      453,  467,  470,  462,  471,  473,  476,  459,  473,  456,
      466,  477,  478,  479,  470,  480,  479,  469,  471,  481,
      483,  486,  483,  485,  476,  491,  477,  490,  485,  487,
      478,  492,  487,  480,  481,  489,  486,  495,  498,  491,
      489,  498,  490,  492,  499,  501,  502,  504,  495,  502,

      501,  496,  494,  493,  488,  484,  482,  475,  504,  499,
      507,  507,  507,  507,  507,  507,  507,  508,  508,  508,
      508,  508,  508,  508,  509,  509,  510,  510,  511,  511,
      511,  512,  474,  512,  512,  512,  512,  512,  513,  472,
      513,  513,  514,  468,  514,  514,  514,  514,  514,  515,
      515,  515,  515,  515,  515,  515,  516,  465,  516,  516,
      517,  463,  517,  517,  517,  517,  517,  518,  518,  518,
      518,  518,  518,  518,  519,  519,  519,  519,  519,  519,
      519,  520,  460,  520,  520,  458,  457,  454,  449,  446,
      445,  444,  443,  438,  436,  435,  434,  431,  420,  419,

      418,  414,  412,  409,  408,  406,  405,  401,  398,  396,
      394,  386,  373,  372,  368,  362,  361,  360,  355,  353,
      329,  324,  321,  320,  317,  307,  303,  276,  268,  266,
      265,  264,  263,  262,  260,  259,  258,  256,  252,  241,
      234,  224,  199,  191,  189,  187,  171,  129,  122,  121,
      101,   88,   73,   72,   67,   62,   60,   50,   26,   25,
       24,   23,    8,    7,    5,    3,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,

      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506,  506,  506,  506,  506,  506,  506,  506,  506,
      506,  506
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "vjass.l"
#line 2 "vjass.l"

#include <stdio.h>
#include "vjass.tab.h"
 
/* line documentation comment */
/* vJass Preprocessor */
/* Jass++ Preprocessor */
/* line comment */
/* new!!! */
#line 877 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 38 "vjass.l"


#line 1062 "lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 507 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1067 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 40 "vjass.l"
{ return StringLiteral; }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 41 "vjass.l"
{ printf( "Non valid escape sequences in string\n" ); }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 42 "vjass.l"
{ return LineDocComment; }
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 43 "vjass.l"
{ return VjassPreprocessor; }
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 44 "vjass.l"
{ return JassppPreprocessor; }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 45 "vjass.l"
{ return LineComment; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "vjass.l"
{ return BlockDocComment; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "vjass.l"
{ return BlockComment; }
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 48 "vjass.l"
{ return NewLine; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 50 "vjass.l"
return BooleanLiteral;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 52 "vjass.l"
return NullKeyword;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 53 "vjass.l"
return TypeKeyword;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 54 "vjass.l"
return ConstantKeyword;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 55 "vjass.l"
return NativeKeyword;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 56 "vjass.l"
return FunctionKeyword;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 57 "vjass.l"
return EndfunctionKeyword;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 58 "vjass.l"
return GlobalsKeyword;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 59 "vjass.l"
return EndglobalsKeyword;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 60 "vjass.l"
return LocalKeyword;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 61 "vjass.l"
return SetKeyword;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 62 "vjass.l"
return CallKeyword;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 63 "vjass.l"
return IfKeyword;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 64 "vjass.l"
return ThenKeyword;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 65 "vjass.l"
return ElseKeyword;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 66 "vjass.l"
return ElseifKeyword;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 67 "vjass.l"
return EndifKeyword;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 68 "vjass.l"
return ReturnKeyword;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 69 "vjass.l"
return LoopKeyword;
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 70 "vjass.l"
return EndloopKeyword;
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 71 "vjass.l"
return ExitwhenKeyword;
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 72 "vjass.l"
return NothingKeyword;
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 73 "vjass.l"
return TakesKeyword;
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 74 "vjass.l"
return ReturnsKeyword;
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 75 "vjass.l"
return ExtendsKeyword;
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 76 "vjass.l"
return ArrayKeyword;
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 77 "vjass.l"
return AndKeyword;
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 78 "vjass.l"
return OrKeyword;
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 79 "vjass.l"
return Dot;
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 80 "vjass.l"
return Comma;
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 81 "vjass.l"
return LeftParenthesis;
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 82 "vjass.l"
return RightParenthesis;
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 83 "vjass.l"
return LeftSquaredBracked;
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 84 "vjass.l"
return RightSquaredBracked;
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 85 "vjass.l"
return SetOperator;
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 86 "vjass.l"
return MultiplicationOperator;
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 87 "vjass.l"
return DivisionOperator;
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 88 "vjass.l"
return PlusOperator;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "vjass.l"
return MinusOperator;
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "vjass.l"
return LessOperator;
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "vjass.l"
return GreaterOperator;
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "vjass.l"
return EqualOperator;
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "vjass.l"
return LessEqualOperator;
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 94 "vjass.l"
return GreaterEqualOperator;
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 95 "vjass.l"
return NotEqualOperator;
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 96 "vjass.l"
return Preprocessor;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 97 "vjass.l"
return MethodKeyword;
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 98 "vjass.l"
return EndmethodKeyword;
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 99 "vjass.l"
return PrivateKeyword;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 100 "vjass.l"
return PublicKeyword;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 101 "vjass.l"
return StaticKeyword;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 102 "vjass.l"
return DebugKeyword;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 103 "vjass.l"
return KeywordKeyword;
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 104 "vjass.l"
return LibraryKeyword;
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 105 "vjass.l"
return Library_onceKeyword;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 106 "vjass.l"
return EndlibraryKeyword;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 107 "vjass.l"
return ScopeKeyword;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 108 "vjass.l"
return EndscopeKeyword;
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 109 "vjass.l"
return StructKeyword;
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 110 "vjass.l"
return EndstructKeyword;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 111 "vjass.l"
return InterfaceKeyword;
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 112 "vjass.l"
return EndinterfaceKeyword;
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 113 "vjass.l"
return DelegateKeyword;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 114 "vjass.l"
return StubKeyword;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 115 "vjass.l"
return ModuleKeyword;
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 116 "vjass.l"
return EndmoduleKeyword;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 117 "vjass.l"
return ImplementKeyword;
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 118 "vjass.l"
return HookKeyword;
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 119 "vjass.l"
return KeyKeyword;
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 120 "vjass.l"
return ImportKeyword;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 121 "vjass.l"
return DovjassinitKeyword;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 122 "vjass.l"
return InjectKeyword;
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 123 "vjass.l"
return EndinjectKeyword;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 124 "vjass.l"
return NovjassKeyword;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 125 "vjass.l"
return EndnovjassKeyword;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 126 "vjass.l"
return VjassKeyword;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 127 "vjass.l"
return EndvjassKeyword;
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 128 "vjass.l"
return ZincKeyword;
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 129 "vjass.l"
return EndzincKeyword;
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 130 "vjass.l"
return ExternalblockKeyword;
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 131 "vjass.l"
return EndexternalblockKeyword;
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 132 "vjass.l"
return LoaddataKeyword;
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 133 "vjass.l"
return ExternalKeyword;
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 134 "vjass.l"
return TextmacroKeyword;
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 135 "vjass.l"
return TextmacroonceKeyword;
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 136 "vjass.l"
return EndtextmacroKeyword;
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 137 "vjass.l"
return RuntextmacroKeyword;
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 138 "vjass.l"
return RequiresKeyword;
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 139 "vjass.l"
return NeedsKeyword;
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 140 "vjass.l"
return UsesKeyword;
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 141 "vjass.l"
return InitializerKeyword;
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 142 "vjass.l"
return DefaultsKeyword;
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 143 "vjass.l"
return OptionalKeyword;
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 144 "vjass.l"
return SuperKeyword;
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 145 "vjass.l"
return ThistypeKeyword;
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 146 "vjass.l"
return OperatorKeyword;
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 147 "vjass.l"
return ExecuteKeyword;
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 148 "vjass.l"
return EvaluateKeyword;
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 149 "vjass.l"
return GlobalKeyword;
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 151 "vjass.l"
{ return RealLiteral; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 153 "vjass.l"
{ return IntegerLiteral; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 155 "vjass.l"
{ return Identifier; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 156 "vjass.l"
{ return UnitTypeIntegerLiteral; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 158 "vjass.l"
/* eat up whitespace */
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 160 "vjass.l"
printf( "Unrecognized character: %s\n", yytext );
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 162 "vjass.l"
ECHO;
	YY_BREAK
#line 1727 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 507 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 507 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 506);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef _UNISTD_H /* assume unistd.h has isatty() for us */
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __THROW /* this is a gnuism */
extern int isatty (int ) __THROW;
#else
extern int isatty (int );
#endif
#ifdef __cplusplus
}
#endif
#endif
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 162 "vjass.l"



