name: CMake CI Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # Run the build every day at 4:00 AM UTC
    - cron: '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest # Use a free Ubuntu runner

    steps:
    - uses: actions/checkout@v4 # Step 1: Checkout your repository code
    
    - name: Install required Ubuntu packages
      run: |
        sudo add-apt-repository universe
        sudo apt-get update
        sudo apt-get install -y cmake-gui gettext libboost-all-dev libjpeg-dev libbz2-dev qtbase5-dev qtmultimedia5-dev libogre-1.12-dev  extra-cmake-modules doxygen
    
    - name: Use the installed package (example)
      run: |
        echo "gettext version is:"
        gettext --version

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBLP=ON -DMPQ=ON -DMDLX=ON -DMAP=ON -DJASS=ON -DAPP=ON -DEDITOR=ON -DUSE_KIOSLAVE=ON -DUSE_QBLP=ON -DUSE_OGREBLP=ON -DGAME=ON -DUSE_MIME=ON -DDOC=ON 

    - name: Build with CMake
      run: cmake --build ${{github.workspace}}/build --config Debug

    - name: Run CTest
      working-directory: ${{github.workspace}}/build
      run: ctest --verbose --output-on-failure
